version: '3'

services:
  web:
    build: .
    restart: 'always'
    ports:
      - '8080:8080'

  db:
    image: 'mongo'
    restart: 'always'
    environment:
      MONGODB_PASSWORD: 'mongodb'
    volumes:
      - db-data:/foo

volumes:
  db-data:
